# Generated by Django 5.2 on 2025-04-23 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core_post", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="post",
            table=None,
        ),
    ]
