# Generated by Django 5.2 on 2025-04-28 20:53

import core.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_comment", "0002_alter_comment_author_alter_comment_post"),
        ("core_user", "0003_user_posts_liked_alter_user_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="comments_liked",
            field=models.ManyToManyField(
                related_name="commented_by", to="core_comment.comment"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to=core.user.models.user_directory_path
            ),
        ),
    ]
